#!/usr/bin/env ruby
gem 'test-unit', '1.2.3' if RUBY_VERSION.to_f >= 1.9

ENV['RAILS_ENV'] ||= 'test'
require File.join(File.dirname(__FILE__), "/../config/environment")

require 'spec/autorun'
exit ::Spec::Runner::CommandLine.run
